#!/usr/bin/perl -i

# Get the release version number
$v = $ENV{ATVERS};
die "Must specify version number by setting version with environment ATVERS" unless $v;

# Get the release date
use POSIX qw(strftime);
$d = $ENV{ATDATE};
if ($d eq '') {
    $d = strftime("%B %e, %Y", (localtime));
}

while (<>) {
    s|^([ \t]+<version>)[^<]+</version>|\1$v</version>|;
    s|^([ \t]+<creationDate>)[^<]+</creationDate>|\1$d</creationDate>|;
    s|^define\('AttachmentsComponentVersion', '([^\']+)'\)|define('AttachmentsComponentVersion', '$v')|;
    s|^\*\*Version [^ ]+ - [^\*]+\*\*$|**Version $v - $d**|;
    print;}
